version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/emails
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OUTLOOK_CLIENT_ID=your_client_id
      - OUTLOOK_CLIENT_SECRET=your_client_secret
      - OUTLOOK_CALLBACK_URL=http://localhost:3000/api/oauth-callback
    depends_on:
      - mongo
      - elasticsearch
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
